### ISSUE TITLE
The `optional` Property Should be `null` when Not Used

### ISSUE THREAD

**Issue by ryanfitzer** [SapientNitroLA/sugarcoat#4]
When the `name` and `type` properties in a tag object from the `tags` array are empty strings, the `optional` property should be `null`. When the value is a `boolean`, it implies that the `optional` property is valid, when it shouldn't even apply.

**Comment by ryanfitzer** [comment]
This will require a new comment parser instead of altering an existing parser. The reason is that all existing ones expect to be parsing only .js files, or don't have the flexibility in comment syntax required.

A [new one](https://github.com/ryanfitzer/comment-serializer) is in-progress.

**Comment by tisAliG** [comment]
@ryanfitzer is this something that still needs to be added to comment-serializer?

**Comment by ryanfitzer** [comment]
@vbalcom Isn't comment-serializer already integrated?

**Comment by tisAliG** [comment]
Yes it is, I believe @vbalcom integrated it.

**Comment by ryanfitzer** [comment]
@tisAliG please verify.

**Comment by tisAliG** [comment]
Verified for myself and with @vbalcom that comment serializer has been integrated. Closing.
